package com.Generator.dao1;

import com.Generator.bean.BdClientContacts;
import com.Generator.bean.BdClientContactsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BdClientContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int countByExample(BdClientContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int deleteByExample(BdClientContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int insert(BdClientContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int insertSelective(BdClientContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    List<BdClientContacts> selectByExample(BdClientContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    BdClientContacts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") BdClientContacts record, @Param("example") BdClientContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int updateByExample(@Param("record") BdClientContacts record, @Param("example") BdClientContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(BdClientContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client_contacts
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    int updateByPrimaryKey(BdClientContacts record);
}