package com.Generator.dao1;

import com.Generator.bean.BdClient1;
import com.Generator.bean.BdClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BdClientMapper1 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int countByExample(BdClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int deleteByExample(BdClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int insert(BdClient1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int insertSelective(BdClient1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    List<BdClient1> selectByExample(BdClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    BdClient1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") BdClient1 record, @Param("example") BdClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int updateByExample(@Param("record") BdClient1 record, @Param("example") BdClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int updateByPrimaryKeySelective(BdClient1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bd_client
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    int updateByPrimaryKey(BdClient1 record);
}