package com.Generator.dao1;

import com.Generator.bean.McStamp;
import com.Generator.bean.McStampExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface McStampMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int countByExample(McStampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int deleteByExample(McStampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int insert(McStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int insertSelective(McStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    List<McStamp> selectByExample(McStampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    McStamp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") McStamp record, @Param("example") McStampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int updateByExample(@Param("record") McStamp record, @Param("example") McStampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int updateByPrimaryKeySelective(McStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_stamp
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    int updateByPrimaryKey(McStamp record);
}