package com.Generator.dao1;

import com.Generator.bean.SysApprovalDetailed;
import com.Generator.bean.SysApprovalDetailedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysApprovalDetailedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int countByExample(SysApprovalDetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int deleteByExample(SysApprovalDetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int insert(SysApprovalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int insertSelective(SysApprovalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    List<SysApprovalDetailed> selectByExample(SysApprovalDetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    SysApprovalDetailed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysApprovalDetailed record, @Param("example") SysApprovalDetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int updateByExample(@Param("record") SysApprovalDetailed record, @Param("example") SysApprovalDetailedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int updateByPrimaryKeySelective(SysApprovalDetailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_approval_detailed
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    int updateByPrimaryKey(SysApprovalDetailed record);
}