package com.Generator.bean;

public class BdClientContacts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.id
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.clientid
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private Integer clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.name
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.role
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.phone
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.mobile
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.wechat
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.email
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client_contacts.content
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.id
     *
     * @return the value of bd_client_contacts.id
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.id
     *
     * @param id the value for bd_client_contacts.id
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.clientid
     *
     * @return the value of bd_client_contacts.clientid
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.clientid
     *
     * @param clientid the value for bd_client_contacts.clientid
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.name
     *
     * @return the value of bd_client_contacts.name
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.name
     *
     * @param name the value for bd_client_contacts.name
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.role
     *
     * @return the value of bd_client_contacts.role
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.role
     *
     * @param role the value for bd_client_contacts.role
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.phone
     *
     * @return the value of bd_client_contacts.phone
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.phone
     *
     * @param phone the value for bd_client_contacts.phone
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.mobile
     *
     * @return the value of bd_client_contacts.mobile
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.mobile
     *
     * @param mobile the value for bd_client_contacts.mobile
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.wechat
     *
     * @return the value of bd_client_contacts.wechat
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.wechat
     *
     * @param wechat the value for bd_client_contacts.wechat
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.email
     *
     * @return the value of bd_client_contacts.email
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.email
     *
     * @param email the value for bd_client_contacts.email
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client_contacts.content
     *
     * @return the value of bd_client_contacts.content
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client_contacts.content
     *
     * @param content the value for bd_client_contacts.content
     *
     * @mbggenerated Tue Mar 05 15:59:54 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}