package com.Generator.bean;

public class BdClient1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.id
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.code
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.name
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.deptid
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.unit_type
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String unitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.userid
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.content
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.phone
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.fax
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.address
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.tfn
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String tfn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.bankaccount
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String bankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.bankname
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bd_client.bankaddress
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    private String bankaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.id
     *
     * @return the value of bd_client.id
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.id
     *
     * @param id the value for bd_client.id
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.code
     *
     * @return the value of bd_client.code
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.code
     *
     * @param code the value for bd_client.code
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.name
     *
     * @return the value of bd_client.name
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.name
     *
     * @param name the value for bd_client.name
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.deptid
     *
     * @return the value of bd_client.deptid
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.deptid
     *
     * @param deptid the value for bd_client.deptid
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.unit_type
     *
     * @return the value of bd_client.unit_type
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.unit_type
     *
     * @param unitType the value for bd_client.unit_type
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setUnitType(String unitType) {
        this.unitType = unitType == null ? null : unitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.userid
     *
     * @return the value of bd_client.userid
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.userid
     *
     * @param userid the value for bd_client.userid
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.content
     *
     * @return the value of bd_client.content
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.content
     *
     * @param content the value for bd_client.content
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.phone
     *
     * @return the value of bd_client.phone
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.phone
     *
     * @param phone the value for bd_client.phone
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.fax
     *
     * @return the value of bd_client.fax
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.fax
     *
     * @param fax the value for bd_client.fax
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.address
     *
     * @return the value of bd_client.address
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.address
     *
     * @param address the value for bd_client.address
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.tfn
     *
     * @return the value of bd_client.tfn
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getTfn() {
        return tfn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.tfn
     *
     * @param tfn the value for bd_client.tfn
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setTfn(String tfn) {
        this.tfn = tfn == null ? null : tfn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.bankaccount
     *
     * @return the value of bd_client.bankaccount
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.bankaccount
     *
     * @param bankaccount the value for bd_client.bankaccount
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount == null ? null : bankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.bankname
     *
     * @return the value of bd_client.bankname
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.bankname
     *
     * @param bankname the value for bd_client.bankname
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bd_client.bankaddress
     *
     * @return the value of bd_client.bankaddress
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public String getBankaddress() {
        return bankaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bd_client.bankaddress
     *
     * @param bankaddress the value for bd_client.bankaddress
     *
     * @mbggenerated Mon Mar 04 10:48:50 CST 2019
     */
    public void setBankaddress(String bankaddress) {
        this.bankaddress = bankaddress == null ? null : bankaddress.trim();
    }
}