package com.Generator.bean;

import java.util.Date;

public class McFileBorrow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.id
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.deptid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.createtime
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.userid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.phone
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.name
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.file_num
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Integer fileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.purpose
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.returntime
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Date returntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.consignee
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.consignee_address
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String consigneeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.consignee_phone
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String consigneePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.accessory
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String accessory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.processid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Integer processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.process_userid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private Integer processUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_file_borrow.process_state
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    private String processState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.id
     *
     * @return the value of mc_file_borrow.id
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.id
     *
     * @param id the value for mc_file_borrow.id
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.deptid
     *
     * @return the value of mc_file_borrow.deptid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.deptid
     *
     * @param deptid the value for mc_file_borrow.deptid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.createtime
     *
     * @return the value of mc_file_borrow.createtime
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.createtime
     *
     * @param createtime the value for mc_file_borrow.createtime
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.userid
     *
     * @return the value of mc_file_borrow.userid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.userid
     *
     * @param userid the value for mc_file_borrow.userid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.phone
     *
     * @return the value of mc_file_borrow.phone
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.phone
     *
     * @param phone the value for mc_file_borrow.phone
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.name
     *
     * @return the value of mc_file_borrow.name
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.name
     *
     * @param name the value for mc_file_borrow.name
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.file_num
     *
     * @return the value of mc_file_borrow.file_num
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Integer getFileNum() {
        return fileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.file_num
     *
     * @param fileNum the value for mc_file_borrow.file_num
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setFileNum(Integer fileNum) {
        this.fileNum = fileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.purpose
     *
     * @return the value of mc_file_borrow.purpose
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.purpose
     *
     * @param purpose the value for mc_file_borrow.purpose
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.returntime
     *
     * @return the value of mc_file_borrow.returntime
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Date getReturntime() {
        return returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.returntime
     *
     * @param returntime the value for mc_file_borrow.returntime
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setReturntime(Date returntime) {
        this.returntime = returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.consignee
     *
     * @return the value of mc_file_borrow.consignee
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.consignee
     *
     * @param consignee the value for mc_file_borrow.consignee
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.consignee_address
     *
     * @return the value of mc_file_borrow.consignee_address
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.consignee_address
     *
     * @param consigneeAddress the value for mc_file_borrow.consignee_address
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.consignee_phone
     *
     * @return the value of mc_file_borrow.consignee_phone
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.consignee_phone
     *
     * @param consigneePhone the value for mc_file_borrow.consignee_phone
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.accessory
     *
     * @return the value of mc_file_borrow.accessory
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getAccessory() {
        return accessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.accessory
     *
     * @param accessory the value for mc_file_borrow.accessory
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setAccessory(String accessory) {
        this.accessory = accessory == null ? null : accessory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.processid
     *
     * @return the value of mc_file_borrow.processid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Integer getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.processid
     *
     * @param processid the value for mc_file_borrow.processid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setProcessid(Integer processid) {
        this.processid = processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.process_userid
     *
     * @return the value of mc_file_borrow.process_userid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public Integer getProcessUserid() {
        return processUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.process_userid
     *
     * @param processUserid the value for mc_file_borrow.process_userid
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setProcessUserid(Integer processUserid) {
        this.processUserid = processUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_file_borrow.process_state
     *
     * @return the value of mc_file_borrow.process_state
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public String getProcessState() {
        return processState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_file_borrow.process_state
     *
     * @param processState the value for mc_file_borrow.process_state
     *
     * @mbggenerated Fri Mar 22 08:57:12 CST 2019
     */
    public void setProcessState(String processState) {
        this.processState = processState == null ? null : processState.trim();
    }
}