package com.Generator.bean;

import java.util.Date;

public class McMaterials {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.id
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.deptid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.createtime
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.projectid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.content
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.offer_tpye
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String offerTpye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.purpose
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.consignee
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.consignee_address
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String consigneeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.consignee_phone
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String consigneePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.accessory
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String accessory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.processid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private Integer processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.process_userid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private Integer processUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_materials.process_state
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    private String processState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.id
     *
     * @return the value of mc_materials.id
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.id
     *
     * @param id the value for mc_materials.id
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.deptid
     *
     * @return the value of mc_materials.deptid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.deptid
     *
     * @param deptid the value for mc_materials.deptid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.createtime
     *
     * @return the value of mc_materials.createtime
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.createtime
     *
     * @param createtime the value for mc_materials.createtime
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.projectid
     *
     * @return the value of mc_materials.projectid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.projectid
     *
     * @param projectid the value for mc_materials.projectid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.content
     *
     * @return the value of mc_materials.content
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.content
     *
     * @param content the value for mc_materials.content
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.offer_tpye
     *
     * @return the value of mc_materials.offer_tpye
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getOfferTpye() {
        return offerTpye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.offer_tpye
     *
     * @param offerTpye the value for mc_materials.offer_tpye
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setOfferTpye(String offerTpye) {
        this.offerTpye = offerTpye == null ? null : offerTpye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.purpose
     *
     * @return the value of mc_materials.purpose
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.purpose
     *
     * @param purpose the value for mc_materials.purpose
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.consignee
     *
     * @return the value of mc_materials.consignee
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.consignee
     *
     * @param consignee the value for mc_materials.consignee
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.consignee_address
     *
     * @return the value of mc_materials.consignee_address
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.consignee_address
     *
     * @param consigneeAddress the value for mc_materials.consignee_address
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.consignee_phone
     *
     * @return the value of mc_materials.consignee_phone
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.consignee_phone
     *
     * @param consigneePhone the value for mc_materials.consignee_phone
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.accessory
     *
     * @return the value of mc_materials.accessory
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getAccessory() {
        return accessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.accessory
     *
     * @param accessory the value for mc_materials.accessory
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setAccessory(String accessory) {
        this.accessory = accessory == null ? null : accessory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.processid
     *
     * @return the value of mc_materials.processid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public Integer getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.processid
     *
     * @param processid the value for mc_materials.processid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setProcessid(Integer processid) {
        this.processid = processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.process_userid
     *
     * @return the value of mc_materials.process_userid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public Integer getProcessUserid() {
        return processUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.process_userid
     *
     * @param processUserid the value for mc_materials.process_userid
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setProcessUserid(Integer processUserid) {
        this.processUserid = processUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_materials.process_state
     *
     * @return the value of mc_materials.process_state
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public String getProcessState() {
        return processState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_materials.process_state
     *
     * @param processState the value for mc_materials.process_state
     *
     * @mbggenerated Wed Mar 27 09:07:48 CST 2019
     */
    public void setProcessState(String processState) {
        this.processState = processState == null ? null : processState.trim();
    }
}