package com.Generator.bean;

import java.util.Date;

public class McStamp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.id
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.deptid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.createtime
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.userid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.phone
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.content
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.file_num
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Integer fileNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.stamp_type
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String stampType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.consignee
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.consignee_address
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String consigneeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.consignee_phone
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String consigneePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.accessory
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String accessory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.processid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Integer processid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.process_userid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Integer processUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.process_state
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private String processState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_stamp.updatetime
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.id
     *
     * @return the value of mc_stamp.id
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.id
     *
     * @param id the value for mc_stamp.id
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.deptid
     *
     * @return the value of mc_stamp.deptid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.deptid
     *
     * @param deptid the value for mc_stamp.deptid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.createtime
     *
     * @return the value of mc_stamp.createtime
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.createtime
     *
     * @param createtime the value for mc_stamp.createtime
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.userid
     *
     * @return the value of mc_stamp.userid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.userid
     *
     * @param userid the value for mc_stamp.userid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.phone
     *
     * @return the value of mc_stamp.phone
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.phone
     *
     * @param phone the value for mc_stamp.phone
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.content
     *
     * @return the value of mc_stamp.content
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.content
     *
     * @param content the value for mc_stamp.content
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.file_num
     *
     * @return the value of mc_stamp.file_num
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Integer getFileNum() {
        return fileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.file_num
     *
     * @param fileNum the value for mc_stamp.file_num
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setFileNum(Integer fileNum) {
        this.fileNum = fileNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.stamp_type
     *
     * @return the value of mc_stamp.stamp_type
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getStampType() {
        return stampType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.stamp_type
     *
     * @param stampType the value for mc_stamp.stamp_type
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setStampType(String stampType) {
        this.stampType = stampType == null ? null : stampType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.consignee
     *
     * @return the value of mc_stamp.consignee
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.consignee
     *
     * @param consignee the value for mc_stamp.consignee
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.consignee_address
     *
     * @return the value of mc_stamp.consignee_address
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.consignee_address
     *
     * @param consigneeAddress the value for mc_stamp.consignee_address
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.consignee_phone
     *
     * @return the value of mc_stamp.consignee_phone
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.consignee_phone
     *
     * @param consigneePhone the value for mc_stamp.consignee_phone
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.accessory
     *
     * @return the value of mc_stamp.accessory
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getAccessory() {
        return accessory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.accessory
     *
     * @param accessory the value for mc_stamp.accessory
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setAccessory(String accessory) {
        this.accessory = accessory == null ? null : accessory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.processid
     *
     * @return the value of mc_stamp.processid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Integer getProcessid() {
        return processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.processid
     *
     * @param processid the value for mc_stamp.processid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setProcessid(Integer processid) {
        this.processid = processid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.process_userid
     *
     * @return the value of mc_stamp.process_userid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Integer getProcessUserid() {
        return processUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.process_userid
     *
     * @param processUserid the value for mc_stamp.process_userid
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setProcessUserid(Integer processUserid) {
        this.processUserid = processUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.process_state
     *
     * @return the value of mc_stamp.process_state
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public String getProcessState() {
        return processState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.process_state
     *
     * @param processState the value for mc_stamp.process_state
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setProcessState(String processState) {
        this.processState = processState == null ? null : processState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mc_stamp.updatetime
     *
     * @return the value of mc_stamp.updatetime
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mc_stamp.updatetime
     *
     * @param updatetime the value for mc_stamp.updatetime
     *
     * @mbggenerated Mon Mar 18 10:02:08 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}