package com.Generator.bean;

import java.util.Date;

public class SysApprovalDetailed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.id
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.approval_name
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private String approvalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.approval_id
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private Integer approvalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.approval_user
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private Integer approvalUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.state
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.approval_date
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private Date approvalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_approval_detailed.opinion
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    private String opinion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.id
     *
     * @return the value of sys_approval_detailed.id
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.id
     *
     * @param id the value for sys_approval_detailed.id
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.approval_name
     *
     * @return the value of sys_approval_detailed.approval_name
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public String getApprovalName() {
        return approvalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.approval_name
     *
     * @param approvalName the value for sys_approval_detailed.approval_name
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setApprovalName(String approvalName) {
        this.approvalName = approvalName == null ? null : approvalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.approval_id
     *
     * @return the value of sys_approval_detailed.approval_id
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public Integer getApprovalId() {
        return approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.approval_id
     *
     * @param approvalId the value for sys_approval_detailed.approval_id
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setApprovalId(Integer approvalId) {
        this.approvalId = approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.approval_user
     *
     * @return the value of sys_approval_detailed.approval_user
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public Integer getApprovalUser() {
        return approvalUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.approval_user
     *
     * @param approvalUser the value for sys_approval_detailed.approval_user
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setApprovalUser(Integer approvalUser) {
        this.approvalUser = approvalUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.state
     *
     * @return the value of sys_approval_detailed.state
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.state
     *
     * @param state the value for sys_approval_detailed.state
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.approval_date
     *
     * @return the value of sys_approval_detailed.approval_date
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public Date getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.approval_date
     *
     * @param approvalDate the value for sys_approval_detailed.approval_date
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_approval_detailed.opinion
     *
     * @return the value of sys_approval_detailed.opinion
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public String getOpinion() {
        return opinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_approval_detailed.opinion
     *
     * @param opinion the value for sys_approval_detailed.opinion
     *
     * @mbggenerated Thu Mar 14 09:55:03 CST 2019
     */
    public void setOpinion(String opinion) {
        this.opinion = opinion == null ? null : opinion.trim();
    }
}